# Change these first
owner: kris8856 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Emby (Media Server)
    url: https://media.lay.scot/emby
    icon: https://media.lay.scot/emby/favicon.ico
  - name: Jellyseerr (Request System)
    url: https://request.media.lay.scot
  - name: Sonarr (TV Downloader)
    url: https://media.lay.scot/sonarr
    icon: https://media.lay.scot/sonarr/Content/Images/logo.svg?h=Q9i1WocFhbrb2NS63sXj5A
  - name: Radarr (Movie Downloader)
    url: https://media.lay.scot/radarr
    icon: https://media.lay.scot/radarr/Content/Images/logo.svg?h=UK+1ymD8NGZtp+MiKdEQRg
  - name: Prowlarr (Download Indexer)
    url: https://media.lay.scot/prowlarr
    icon: https://media.lay.scot/prowlarr/Content/Images/logo.svg?h=8opO029fk/f1FoGMvxi9uw
  - name: Sabnzbd (Usenet Downloader)
    url: https://media.lay.scot/sabnzbd
    icon: https://media.lay.scot/sabnzbd/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.media.lay.scot
  theme: dark
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Kris' Media Server Uptime
  introTitle: "If there's an issue, I'm probably already working on it."
  introMessage: This is a status page which uses **real-time** data from the servers.
  navbar:
    - title: Kris' Media Server Status
      href: https://media.lay.scot/emby

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
